### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by timswhatever** [stephanlensky/marketplace-notifier-bot#91]
> [ERROR] hyacinth.monitor Error polling search SearchSpec(id=2, plugin_path=plugins.marketplace.plugin:MarketplacePlugin, search_params=location='(removed)' category='vehicles')
service-1  | Traceback (most recent call last):
service-1  |   File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
service-1  |     listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
service-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
service-1  |     return await get_listings(search_params, after_time, limit)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/plugins/marketplace/client.py", line 28, in get_listings
service-1  |     async for listing in search:
service-1  |   File "/app/plugins/marketplace/client.py", line 64, in _search
service-1  |     result_content = await _navigate_to_listing_and_get_content(result_page, url)
service-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/plugins/marketplace/client.py", line 106, in _navigate_to_listing_and_get_content
service-1  |     await page.goto(url)
service-1  |   File "/app/hyacinth/util/scraping.py", line 59, in goto_with_log
service-1  |     await old_goto(url, timeout=timeout, wait_until=wait_until, referer=referer)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/async_api/_generated.py", line 8657, in goto
service-1  |     await self._impl_obj.goto(
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_page.py", line 519, in goto
service-1  |     return await self._main_frame.goto(**locals_to_params(locals()))
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 145, in goto
service-1  |     await self._channel.send("goto", locals_to_params(locals()))
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
service-1  |     return await self._connection.wrap_api_call(
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
service-1  |     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
service-1  | playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
service-1  | Call log:
service-1  | navigating to "https://www.facebook.com/marketplace/item/480800291184244/", waiting until "load"
service-1  | 
service-1  | 2024-11-26 16:00:24 [9] [INFO] hyacinth.util.crash_report Saving error report to logs/poll_failure_2024-11-26T16:00:24.635432.txt
service-1  | Job "SearchMonitor.poll_search (trigger: interval[0:10:00], next run at: 2024-11-26 16:09:47 UTC)" raised an exception
service-1  | Traceback (most recent call last):
service-1  |   File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
service-1  |     listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
service-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
service-1  |     return await get_listings(search_params, after_time, limit)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/plugins/marketplace/client.py", line 28, in get_listings
service-1  |     async for listing in search:
service-1  |   File "/app/plugins/marketplace/client.py", line 64, in _search
service-1  |     result_content = await _navigate_to_listing_and_get_content(result_page, url)
service-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/plugins/marketplace/client.py", line 106, in _navigate_to_listing_and_get_content
service-1  |     await page.goto(url)
service-1  |   File "/app/hyacinth/util/scraping.py", line 59, in goto_with_log
service-1  |     await old_goto(url, timeout=timeout, wait_until=wait_until, referer=referer)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/async_api/_generated.py", line 8657, in goto
service-1  |     await self._impl_obj.goto(
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_page.py", line 519, in goto
service-1  |     return await self._main_frame.goto(**locals_to_params(locals()))
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 145, in goto
service-1  |     await self._channel.send("goto", locals_to_params(locals()))
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
service-1  |     return await self._connection.wrap_api_call(
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
service-1  |     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
service-1  | playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
service-1  | Call log:
service-1  | navigating to "https://www.facebook.com/marketplace/item/480800291184244/", waiting until "load"
service-1  | 
service-1  | 
service-1  | During handling of the above exception, another exception occurred:
service-1  | 
service-1  | Traceback (most recent call last):
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
service-1  |     retval = await job.func(*job.args, **job.kwargs)
service-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/hyacinth/monitor.py", line 82, in poll_search
service-1  |     listings = await self.__safe_poll_search(search_spec, after_time)
service-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/hyacinth/monitor.py", line 98, in __safe_poll_search
service-1  |     save_poll_failure_report(e)
service-1  |   File "/app/hyacinth/util/crash_report.py", line 24, in save_poll_failure_report
service-1  |     fname.parent.mkdir(parents=True, exist_ok=True)
service-1  |   File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
service-1  |     os.mkdir(self, mode)
service-1  | PermissionError: [Errno 13] Permission denied: 'logs'

Looks to be both a permission error and/or a timeout error? Haven't gotten any Facebook notifications.
Running on a Proxmox LXC

**Comment by edisonmamani176-source** [comment]
encontre una aplicacion que hace lo mismo con mas funcionalidades talvez te sirva "https://firupost.netlify.app/docs" espero te ayude
